# Generated by Django 4.1.3 on 2022-11-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maker",
            name="name",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
