# Generated by Django 4.1.3 on 2022-11-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_maker_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="title",
        ),
    ]
